### ISSUE TITLE
Do you have screenshots for keep a view before try install it?

### ISSUE THREAD

**Issue by johnfelipe** [troy-open-data/legislative_twitter#48]

**Comment by leesharma** [comment]
To make sure I understand your question: are you asking if I have screenshots of the app running so that you can see what it looks like without installing it?

This app is still in initial development, so I wouldn't install this just yet; I'm hoping to put out the first stable release in a few weeks. As part of that, I'm writing some user documentation; I can link it here when I have something more detailed up.

Here are a few screenshots I just took on my development machine:

The Meetings page:
![Meetings/calendar page](https://cloud.githubusercontent.com/assets/814638/10810383/e1912b62-7dd6-11e5-8756-47dc738401d7.png)
The Bills page, full screen:
![The Bills page, full screen](https://cloud.githubusercontent.com/assets/814638/10810382/dbda250c-7dd6-11e5-826f-ab71612ee6ea.png)
The Bills page after signing in as an admin:
![The Bills page after I signed in as an administrator](https://cloud.githubusercontent.com/assets/814638/10810386/e486156c-7dd6-11e5-90c8-eb7d8472aada.png)
On mobile:
![Mobile view](https://cloud.githubusercontent.com/assets/814638/10810390/e73899ce-7dd6-11e5-98f5-9edb41a382d1.png)
Mobile navigation menu:
![Mobile navigation](https://cloud.githubusercontent.com/assets/814638/10810391/e8cd7232-7dd6-11e5-8c15-a2f40861c39c.png)

Let me know if you have any further questions!
